-- MySQL Script generated by MySQL Workbench
-- Mon Sep 28 17:28:02 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CarnetVirtualDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CarnetVirtualDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CarnetVirtualDB` DEFAULT CHARACTER SET utf8 ;
USE `CarnetVirtualDB` ;

-- -----------------------------------------------------
-- Table `CarnetVirtualDB`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarnetVirtualDB`.`Rol` (
  `IdRol` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`IdRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CarnetVirtualDB`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarnetVirtualDB`.`Usuario` (
  `IdUsuario` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(16) NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  `Token` VARCHAR(512) NULL,
  `Rol_IdRol` INT NOT NULL,
  PRIMARY KEY (`IdUsuario`),
  CONSTRAINT `fk_Usuario_Rol1`
    FOREIGN KEY (`Rol_IdRol`)
    REFERENCES `CarnetVirtualDB`.`Rol` (`IdRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_Usuario_Rol1_idx` ON `CarnetVirtualDB`.`Usuario` (`Rol_IdRol` ASC);


-- -----------------------------------------------------
-- Table `CarnetVirtualDB`.`Farmacia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarnetVirtualDB`.`Farmacia` (
  `Run_Farmacia` INT NOT NULL,
  `Nombres` VARCHAR(256) NOT NULL,
  `Apellidos` VARCHAR(256) NOT NULL,
  `Telefono` VARCHAR(9) NOT NULL,
  `Password` VARCHAR(512) NOT NULL,
  `Fecha_Nacimiento` VARCHAR(10) NOT NULL,
  `Cargo` VARCHAR(50) NOT NULL,
  `Usuario_IdUsuario` INT NOT NULL,
  PRIMARY KEY (`Run_Farmacia`),
  CONSTRAINT `fk_Farmacia_Usuario1`
    FOREIGN KEY (`Usuario_IdUsuario`)
    REFERENCES `CarnetVirtualDB`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Farmacia_Usuario1_idx` ON `CarnetVirtualDB`.`Farmacia` (`Usuario_IdUsuario` ASC);


-- -----------------------------------------------------
-- Table `CarnetVirtualDB`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarnetVirtualDB`.`Paciente` (
  `Run_Paciente` VARCHAR(9) NOT NULL,
  `Nombres` VARCHAR(256) NOT NULL,
  `Apellidos` VARCHAR(256) NOT NULL,
  `Fecha_Nacimiento` VARCHAR(10) NOT NULL,
  `Telefono` VARCHAR(9) NOT NULL,
  `Password` VARCHAR(512) NOT NULL,
  `Usuario_IdUsuario` INT NOT NULL,
  PRIMARY KEY (`Run_Paciente`),
  CONSTRAINT `fk_Paciente_Usuario1`
    FOREIGN KEY (`Usuario_IdUsuario`)
    REFERENCES `CarnetVirtualDB`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Paciente_Usuario1_idx` ON `CarnetVirtualDB`.`Paciente` (`Usuario_IdUsuario` ASC) ;


-- -----------------------------------------------------
-- Table `CarnetVirtualDB`.`Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarnetVirtualDB`.`Medico` (
  `Run_Medico` VARCHAR(9) NOT NULL,
  `Nombres` VARCHAR(256) NOT NULL,
  `Apellidos` VARCHAR(256) NOT NULL,
  `Telefono` INT NOT NULL,
  `Especialidad` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(512) NOT NULL,
  `Fecha_Nacimiento` VARCHAR(45) NOT NULL,
  `Usuario_IdUsuario` INT NOT NULL,
  PRIMARY KEY (`Run_Medico`),
  CONSTRAINT `fk_Medico_Usuario1`
    FOREIGN KEY (`Usuario_IdUsuario`)
    REFERENCES `CarnetVirtualDB`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Medico_Usuario1_idx` ON `CarnetVirtualDB`.`Medico` (`Usuario_IdUsuario` ASC);


-- -----------------------------------------------------
-- Table `CarnetVirtualDB`.`Receta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarnetVirtualDB`.`Receta` (
  `idReceta` INT NOT NULL AUTO_INCREMENT,
  `Fecha_Emision` VARCHAR(10) NOT NULL,
  `Prescripcion` VARCHAR(256) NOT NULL,
  `Indicaciones` VARCHAR(512) NOT NULL,
  `Estado` VARCHAR(256) NOT NULL,
  `Farmacia_Run_Farmacia` INT NOT NULL,
  `Paciente_Run_Paciente` VARCHAR(9) NOT NULL,
  `Medico_Run_Medico` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`idReceta`, `Farmacia_Run_Farmacia`, `Paciente_Run_Paciente`),
  CONSTRAINT `fk_Receta_Farmacia1`
    FOREIGN KEY (`Farmacia_Run_Farmacia`)
    REFERENCES `CarnetVirtualDB`.`Farmacia` (`Run_Farmacia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Receta_Paciente1`
    FOREIGN KEY (`Paciente_Run_Paciente`)
    REFERENCES `CarnetVirtualDB`.`Paciente` (`Run_Paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Receta_Medico1`
    FOREIGN KEY (`Medico_Run_Medico`)
    REFERENCES `CarnetVirtualDB`.`Medico` (`Run_Medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Receta_Farmacia1_idx` ON `CarnetVirtualDB`.`Receta` (`Farmacia_Run_Farmacia` ASC) ;

CREATE INDEX `fk_Receta_Paciente1_idx` ON `CarnetVirtualDB`.`Receta` (`Paciente_Run_Paciente` ASC);

CREATE INDEX `fk_Receta_Medico1_idx` ON `CarnetVirtualDB`.`Receta` (`Medico_Run_Medico` ASC) ;


-- -----------------------------------------------------
-- Table `CarnetVirtualDB`.`Meson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarnetVirtualDB`.`Meson` (
  `Run_Meson` VARCHAR(9) NOT NULL,
  `Nombres` VARCHAR(256) NOT NULL,
  `Apellidos` VARCHAR(256) NOT NULL,
  `Telefono` INT NOT NULL,
  `Fecha_Nacimiento` VARCHAR(45) NOT NULL,
  `Cargo` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(512) NOT NULL,
  `Usuario_IdUsuario` INT NOT NULL,
  PRIMARY KEY (`Run_Meson`),
  CONSTRAINT `fk_Meson_Usuario1`
    FOREIGN KEY (`Usuario_IdUsuario`)
    REFERENCES `CarnetVirtualDB`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Meson_Usuario1_idx` ON `CarnetVirtualDB`.`Meson` (`Usuario_IdUsuario` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarnetVirtualDB`.`Cita` (
  `IdCita` INT NOT NULL AUTO_INCREMENT,
  `Fecha` VARCHAR(10) NOT NULL,
  `Hora` VARCHAR(45) NOT NULL,
  `Estado` VARCHAR(256) NOT NULL,
  `Medico_Run_Medico` VARCHAR(9) NOT NULL,
  `Meson_Run_Meson` VARCHAR(9) NOT NULL,
  `Paciente_Run_Paciente` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`IdCita`, `Medico_Run_Medico`, `Meson_Run_Meson`),
  CONSTRAINT `fk_Cita_Medico1`
    FOREIGN KEY (`Medico_Run_Medico`)
    REFERENCES `CarnetVirtualDB`.`Medico` (`Run_Medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cita_Meson1`
    FOREIGN KEY (`Meson_Run_Meson`)
    REFERENCES `CarnetVirtualDB`.`Meson` (`Run_Meson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cita_Paciente1`
    FOREIGN KEY (`Paciente_Run_Paciente`)
    REFERENCES `CarnetVirtualDB`.`Paciente` (`Run_Paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Cita_Medico1_idx` ON `CarnetVirtualDB`.`Cita` (`Medico_Run_Medico` ASC) ;

CREATE INDEX `fk_Cita_Meson1_idx` ON `CarnetVirtualDB`.`Cita` (`Meson_Run_Meson` ASC) ;

CREATE INDEX `fk_Cita_Paciente1_idx` ON `CarnetVirtualDB`.`Cita` (`Paciente_Run_Paciente` ASC) ;


-- -----------------------------------------------------
-- Table `CarnetVirtualDB`.`Incidencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarnetVirtualDB`.`Incidencia` (
  `idIncidencia` INT NOT NULL AUTO_INCREMENT,
  `Fecha` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(256) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idIncidencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cita_has_Incidencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarnetVirtualDB`.`Cita_has_Incidencia` (
  `Cita_IdCita` INT NOT NULL,
  `Incidencia_idIncidencia` INT NOT NULL,
  PRIMARY KEY (`Cita_IdCita`, `Incidencia_idIncidencia`),
  CONSTRAINT `fk_Cita_has_Incidencia_Cita`
    FOREIGN KEY (`Cita_IdCita`)
    REFERENCES `CarnetVirtualDB`.`Cita` (`IdCita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cita_has_Incidencia_Incidencia1`
    FOREIGN KEY (`Incidencia_idIncidencia`)
    REFERENCES `CarnetVirtualDB`.`Incidencia` (`idIncidencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Cita_has_Incidencia_Incidencia1_idx` ON `CarnetVirtualDB`.`Cita_has_Incidencia` (`Incidencia_idIncidencia` ASC) ;

CREATE INDEX `fk_Cita_has_Incidencia_Cita_idx` ON `CarnetVirtualDB`.`Cita_has_Incidencia` (`Cita_IdCita` ASC) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
